package com.salk.legacy.product.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.salk.legacy.domain.Item;
import com.salk.legacy.domain.ItemExample;

public interface ItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int countByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int insert(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	List<Item> selectByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	Item selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table item
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Item record);

	List<Item> getItemsByPage(ItemExample example);

	int deleteByPrimaryKeys(@Param("ids") String[] ids);
}