package com.salk.legacy.domain;

import java.util.Date;

public class Import {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.id
	 * 
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_no
	 * 
	 * @mbggenerated
	 */
	private String importNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_size
	 * 
	 * @mbggenerated
	 */
	private String importSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_date
	 * 
	 * @mbggenerated
	 */
	private Date importDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_type
	 * 
	 * @mbggenerated
	 */
	private String importType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.remark
	 * 
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_color
	 * 
	 * @mbggenerated
	 */
	private String importColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.adder_name
	 * 
	 * @mbggenerated
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.add_time
	 * 
	 * @mbggenerated
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.updater_name
	 * 
	 * @mbggenerated
	 */
	private String updaterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.update_time
	 * 
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.is_lock
	 * 
	 * @mbggenerated
	 */
	private String isLock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.status
	 * 
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_name
	 * 
	 * @mbggenerated
	 */
	private String importName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.nums
	 * 
	 * @mbggenerated
	 */
	private Integer nums;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column import.import_prod_id
	 * 
	 * @mbggenerated
	 */
	private String importProdId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.id
	 * 
	 * @return the value of import.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.id
	 * 
	 * @param id
	 *            the value for import.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_no
	 * 
	 * @return the value of import.import_no
	 * @mbggenerated
	 */
	public String getImportNo() {
		return importNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_no
	 * 
	 * @param importNo
	 *            the value for import.import_no
	 * @mbggenerated
	 */
	public void setImportNo(String importNo) {
		this.importNo = importNo == null ? null : importNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_size
	 * 
	 * @return the value of import.import_size
	 * @mbggenerated
	 */
	public String getImportSize() {
		return importSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_size
	 * 
	 * @param importSize
	 *            the value for import.import_size
	 * @mbggenerated
	 */
	public void setImportSize(String importSize) {
		this.importSize = importSize == null ? null : importSize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_date
	 * 
	 * @return the value of import.import_date
	 * @mbggenerated
	 */
	public Date getImportDate() {
		return importDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_date
	 * 
	 * @param importDate
	 *            the value for import.import_date
	 * @mbggenerated
	 */
	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_type
	 * 
	 * @return the value of import.import_type
	 * @mbggenerated
	 */
	public String getImportType() {
		return importType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_type
	 * 
	 * @param importType
	 *            the value for import.import_type
	 * @mbggenerated
	 */
	public void setImportType(String importType) {
		this.importType = importType == null ? null : importType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.remark
	 * 
	 * @return the value of import.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.remark
	 * 
	 * @param remark
	 *            the value for import.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_color
	 * 
	 * @return the value of import.import_color
	 * @mbggenerated
	 */
	public String getImportColor() {
		return importColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_color
	 * 
	 * @param importColor
	 *            the value for import.import_color
	 * @mbggenerated
	 */
	public void setImportColor(String importColor) {
		this.importColor = importColor == null ? null : importColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.adder_name
	 * 
	 * @return the value of import.adder_name
	 * @mbggenerated
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.adder_name
	 * 
	 * @param adderName
	 *            the value for import.adder_name
	 * @mbggenerated
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.add_time
	 * 
	 * @return the value of import.add_time
	 * @mbggenerated
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.add_time
	 * 
	 * @param addTime
	 *            the value for import.add_time
	 * @mbggenerated
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.updater_name
	 * 
	 * @return the value of import.updater_name
	 * @mbggenerated
	 */
	public String getUpdaterName() {
		return updaterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.updater_name
	 * 
	 * @param updaterName
	 *            the value for import.updater_name
	 * @mbggenerated
	 */
	public void setUpdaterName(String updaterName) {
		this.updaterName = updaterName == null ? null : updaterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.update_time
	 * 
	 * @return the value of import.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.update_time
	 * 
	 * @param updateTime
	 *            the value for import.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.is_lock
	 * 
	 * @return the value of import.is_lock
	 * @mbggenerated
	 */
	public String getIsLock() {
		return isLock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.is_lock
	 * 
	 * @param isLock
	 *            the value for import.is_lock
	 * @mbggenerated
	 */
	public void setIsLock(String isLock) {
		this.isLock = isLock == null ? null : isLock.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.status
	 * 
	 * @return the value of import.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.status
	 * 
	 * @param status
	 *            the value for import.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_name
	 * 
	 * @return the value of import.import_name
	 * @mbggenerated
	 */
	public String getImportName() {
		return importName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_name
	 * 
	 * @param importName
	 *            the value for import.import_name
	 * @mbggenerated
	 */
	public void setImportName(String importName) {
		this.importName = importName == null ? null : importName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.nums
	 * 
	 * @return the value of import.nums
	 * @mbggenerated
	 */
	public Integer getNums() {
		return nums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.nums
	 * 
	 * @param nums
	 *            the value for import.nums
	 * @mbggenerated
	 */
	public void setNums(Integer nums) {
		this.nums = nums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column import.import_prod_id
	 * 
	 * @return the value of import.import_prod_id
	 * @mbggenerated
	 */
	public String getImportProdId() {
		return importProdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column import.import_prod_id
	 * 
	 * @param importProdId
	 *            the value for import.import_prod_id
	 * @mbggenerated
	 */
	public void setImportProdId(String importProdId) {
		this.importProdId = importProdId;
	}

	private String strImportDate;
	private long count;

	public long getCount() {
		return count;
	}

	public void setCount(long count) {
		this.count = count;
	}

	public String getStrImportDate() {
		return strImportDate;
	}

	public void setStrImportDate(String strImportDate) {
		this.strImportDate = strImportDate;
	}

}