package com.salk.legacy.domain;

public class Item {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.type_name
	 * @mbggenerated
	 */
	private String typeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.id
	 * @return  the value of item.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.id
	 * @param id  the value for item.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.type_name
	 * @return  the value of item.type_name
	 * @mbggenerated
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.type_name
	 * @param typeName  the value for item.type_name
	 * @mbggenerated
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName == null ? null : typeName.trim();
	}
}